#by default for local deployment - local machine IP is set
backendInstances:
  - myinstantchat.org:12443

domain: "myinstantchat.org"

backendHttpSchema: "https"

http:
  timeoutSec: 30

shutdownWaitTimeoutSec: 10

logging:
  logMaxSizeMb: 100
  logMaxFilesToKeep: 3
  logMaxFileAgeDays: 60

forbiddenRoomNames:
  - metrics
  - ctrl
  - ctrl_rooms
  - ws_entry
  - hw
  - dashboards
  - about
  - terms-of-service
  - privacy-policy
  - control_page_proxy
  - favicon.ico
  - ctrl_command
  - connection-methods
  - universal-access
  - app-win
  - app-win-version
  - direct_retrieval

ctrlAuthLogin: "admin132"
ctrlAuthPasswd: "password132"

clientAgreementVersion: 2

userDrawingEnabled: true

mainHttpSchema: "https"

cookies:
    isSecure: true

unsecureTestMode: false
