#for local deployment with single backend instance - set just local machine IP
backendInstances:
  - 192.168.1.101:8080
  - 192.168.1.102:8080
  - 192.168.1.103:8080

domain: "192.168.1.100"

backendHttpSchema: "http"

http:
  port: ":8080"
  timeoutSec: 30

shutdownWaitTimeoutSec: 10

logging:
  logMaxSizeMb: 100
  logMaxFilesToKeep: 3
  logMaxFileAgeDays: 60

forbiddenRoomNames:
  - metrics
  - ctrl
  - ctrl_rooms
  - ws_entry
  - hw
  - dashboards
  - about
  - control_page_proxy
  - favicon.ico

ctrlAuthLogin: "admin111"
ctrlAuthPasswd: "password111"


# ENV SPECIFIC

#values: dev / prod
envType: "dev"

mainHttpSchemaProd: "https"
mainHttpSchemaDev: "http"

cookiesProd:
    isSecure: true

cookiesDev:
    isSecure: false

