#even for local setup - set local machine's IP to 'allowedOrigins' and use it instead of localhost. NO TRAILING SLASHES
allowedOrigins:
  - https://myinstantchat.org

domain: "myinstantchat.org"

httpSchema: "https"

http:
  port: ":443"
  timeoutSec: 30

shutdownWaitTimeoutSec: 10

logging:
  logMaxSizeMb: 100
  logMaxFilesToKeep: 3
  logMaxFileAgeDays: 60

forbiddenRoomNames:
  - metrics
  - ctrl
  - ctrl_rooms
  - ws_entry
  - hw
  - dashboards
  - about
  - terms-of-service
  - privacy-policy
  - control_page_proxy
  - favicon.ico
  - ctrl_command
  - connection-methods
  - app-win
  - app-win-version
  - direct_retrieval

ctrlAuthLogin: "admin132"
ctrlAuthPasswd: "password132"
